{% set name = "svgelements" %}
{% set version = "1.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/svgelements-{{ version }}.tar.gz
  sha256: 7c02ad6404cd3d1771fd50e40fbfc0550b0893933466f86a6eb815f3ba3f37f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - svgelements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/meerk40t/svgelements
  summary: Svg Elements Parsing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
